#!/usr/bin/env bash
# Builds supabase/rebuild.sql: every migration in order, then the product list.
# Paste that one file into a NEW Supabase project's SQL editor to recreate the database.
set -euo pipefail
cd "$(dirname "$0")"
out=rebuild.sql
{
  echo "-- Lhyndahan: full database rebuild (generated by build-rebuild.sh, do not edit by hand)."
  echo "-- Run once in a brand-new Supabase project. Afterwards run the 'after rebuild' steps in the README."
  for f in migrations/*.sql; do
    echo
    echo "-- ===== $f ====="
    cat "$f"
  done
  echo
  echo "-- ===== seed.sql ====="
  cat seed.sql
} > "$out"
echo "wrote $out ($(wc -l < "$out") lines)"
