-- Lhyndahan: full database rebuild (generated by build-rebuild.sh, do not edit by hand).
-- Run once in a brand-new Supabase project. Afterwards run the 'after rebuild' steps in the README.

-- ===== migrations/0001_init.sql =====
-- =====================================================================
-- Hopia Store — core schema
-- Run once in Supabase: Dashboard → SQL Editor → paste → Run.
-- =====================================================================

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------
-- Settings (exactly one row)
-- ---------------------------------------------------------------------
create table public.settings (
  id                  int primary key default 1 check (id = 1),
  admin_email         text not null default '',
  notify_email        text not null default '',
  gcash_qr_path       text,
  gcash_name          text,
  gcash_number        text,
  -- 0 = Sunday … 3 = Wednesday … 6 = Saturday (Asia/Manila)
  cutoff_dow          int  not null default 3 check (cutoff_dow between 0 and 6),
  cutoff_time         time not null default '23:59',
  -- delivery days counted from the cutoff day (Wed + 2 = Fri, Wed + 3 = Sat)
  office_offset_days  int  not null default 2 check (office_offset_days between 1 and 6),
  outside_offset_days int  not null default 3 check (outside_offset_days between 1 and 6),
  updated_at          timestamptz not null default now()
);
insert into public.settings (id) values (1);

-- ---------------------------------------------------------------------
-- Products
-- ---------------------------------------------------------------------
create type public.bakery as enum ('Ribbonets', 'RSF Bakery', 'D'' Original', 'Edson Hopia Tipas');

create table public.products (
  id               uuid primary key default gen_random_uuid(),
  slug             text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  name             text not null check (length(trim(name)) between 1 and 120),
  bakery           public.bakery not null default 'Ribbonets',
  description      text not null default '',
  supplier_price   numeric(10,2) not null check (supplier_price >= 0),
  selling_price    numeric(10,2) not null check (selling_price >= 0),
  delivery_markup  numeric(10,2) not null default 10 check (delivery_markup >= 0),
  profit_per_piece numeric(10,2) generated always as (selling_price - delivery_markup - supplier_price) stored,
  is_active        boolean not null default false,
  sort_order       int not null default 0,
  deleted_at       timestamptz,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create table public.product_images (
  id          uuid primary key default gen_random_uuid(),
  product_id  uuid not null references public.products on delete cascade,
  path        text not null,           -- object path inside the product-images bucket
  sort_order  int  not null default 0,
  is_primary  boolean not null default false,
  created_at  timestamptz not null default now()
);
create index product_images_product_idx on public.product_images (product_id, sort_order);
create unique index product_images_one_primary on public.product_images (product_id) where is_primary;

-- ---------------------------------------------------------------------
-- Batches (one per weekly cycle; created on demand, never by a cron)
-- A batch covers [starts_at, cutoff_at). cutoff_at is the first instant
-- AFTER the cutoff minute, e.g. Wed 23:59 cutoff → Thu 00:00 Manila.
-- ---------------------------------------------------------------------
create table public.batches (
  id                  uuid primary key default gen_random_uuid(),
  code                text not null unique,      -- cutoff date, e.g. 2026-10-07
  starts_at           timestamptz not null,
  cutoff_at           timestamptz not null unique,
  office_date         date not null,
  outside_date        date not null,
  supplier_ordered_at timestamptz,
  created_at          timestamptz not null default now(),
  check (starts_at < cutoff_at)
);

-- ---------------------------------------------------------------------
-- Customers (built from orders, keyed by normalized phone)
-- ---------------------------------------------------------------------
create table public.customers (
  id         uuid primary key default gen_random_uuid(),
  phone      text not null unique check (phone ~ '^\+639[0-9]{9}$'),
  name       text not null,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- Orders
-- ---------------------------------------------------------------------
create type public.order_status   as enum ('pending', 'ordered', 'delivered', 'cancelled');
create type public.delivery_type  as enum ('office', 'outside');
create type public.payment_method as enum ('cod', 'gcash');

create sequence public.order_no_seq;

create table public.orders (
  id             uuid primary key default gen_random_uuid(),
  order_no       int  not null unique default nextval('public.order_no_seq'),
  code           text generated always as (
                   'LH-' || case when order_no < 10000 then lpad(order_no::text, 4, '0') else order_no::text end
                 ) stored,
  batch_id       uuid not null references public.batches,
  customer_id    uuid not null references public.customers,
  name           text not null,
  phone          text not null check (phone ~ '^\+639[0-9]{9}$'),
  delivery_type  public.delivery_type not null,
  address        text not null check (length(trim(address)) >= 5),
  landmark       text not null check (length(trim(landmark)) >= 2),
  map_url        text,
  notes          text,
  delivery_date  date not null,
  payment_method public.payment_method not null,
  status         public.order_status not null default 'pending',
  paid           boolean not null default false,
  paid_at        timestamptz,
  ordered_at     timestamptz,
  delivered_at   timestamptz,
  cancelled_at   timestamptz,
  seen_by_admin  boolean not null default false,
  total          numeric(10,2) not null check (total >= 0),
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
alter sequence public.order_no_seq owned by public.orders.order_no;
create unique index orders_code_idx on public.orders (code);
create index orders_batch_idx    on public.orders (batch_id, status);
create index orders_customer_idx on public.orders (customer_id, created_at desc);

create table public.order_items (
  id              uuid primary key default gen_random_uuid(),
  order_id        uuid not null references public.orders on delete cascade,
  product_id      uuid references public.products on delete set null,
  -- snapshots: editing a product later never changes past orders or profit
  product_name    text not null,
  qty             int  not null check (qty between 1 and 99),
  selling_price   numeric(10,2) not null,
  supplier_price  numeric(10,2) not null,
  delivery_markup numeric(10,2) not null
);
create index order_items_order_idx on public.order_items (order_id);

-- Spam protection for order creation (written only by the server).
create table public.order_attempts (
  id         bigint generated always as identity primary key,
  ip_hash    text not null,
  created_at timestamptz not null default now()
);
create index order_attempts_ip_idx on public.order_attempts (ip_hash, created_at desc);

-- ---------------------------------------------------------------------
-- updated_at trigger
-- ---------------------------------------------------------------------
create or replace function public.touch_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

create trigger settings_touch before update on public.settings for each row execute function public.touch_updated_at();
create trigger products_touch before update on public.products for each row execute function public.touch_updated_at();
create trigger orders_touch   before update on public.orders   for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------
-- Batch logic
-- ---------------------------------------------------------------------
-- Returns the batch an order placed at `ts` belongs to, creating it if needed.
create or replace function public.get_or_create_batch(ts timestamptz default now())
returns public.batches
language plpgsql
security definer
set search_path = public
as $$
declare
  s          public.settings;
  b          public.batches;
  local_ts   timestamp := ts at time zone 'Asia/Manila';
  cutoff_day date;
  cutoff_end timestamptz;
  prev_end   timestamptz;
begin
  select * into b from public.batches where starts_at <= ts and ts < cutoff_at;
  if found then
    return b;
  end if;

  select * into s from public.settings where id = 1;

  -- next cutoff day on/after today (Manila)
  cutoff_day := local_ts::date + ((s.cutoff_dow - extract(dow from local_ts)::int + 7) % 7);
  cutoff_end := ((cutoff_day + s.cutoff_time) + interval '1 minute') at time zone 'Asia/Manila';
  if cutoff_end <= ts then
    cutoff_day := cutoff_day + 7;
    cutoff_end := cutoff_end + interval '7 days';
  end if;

  -- never overlap an earlier batch (matters only if the cutoff setting changed)
  select max(cutoff_at) into prev_end from public.batches where cutoff_at <= ts;

  insert into public.batches (code, starts_at, cutoff_at, office_date, outside_date)
  values (
    to_char(cutoff_day, 'YYYY-MM-DD'),
    greatest(cutoff_end - interval '7 days', coalesce(prev_end, '-infinity'::timestamptz)),
    cutoff_end,
    cutoff_day + s.office_offset_days,
    cutoff_day + s.outside_offset_days
  )
  on conflict do nothing;

  select * into b from public.batches where starts_at <= ts and ts < cutoff_at;
  if not found then
    raise exception 'Could not resolve batch for %', ts;
  end if;
  return b;
end $$;

-- ---------------------------------------------------------------------
-- Admin check: the logged-in email must match settings.admin_email
-- ---------------------------------------------------------------------
create or replace function public.is_admin() returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.settings
    where admin_email <> ''
      and lower(admin_email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

-- Non-secret settings the storefront needs.
create or replace function public.get_public_settings()
returns table (
  gcash_qr_path text, gcash_name text, gcash_number text,
  cutoff_dow int, cutoff_time time, office_offset_days int, outside_offset_days int
)
language sql
stable
security definer
set search_path = public
as $$
  select gcash_qr_path, gcash_name, gcash_number,
         cutoff_dow, cutoff_time, office_offset_days, outside_offset_days
  from public.settings where id = 1;
$$;

-- ===== migrations/0002_security.sql =====
-- =====================================================================
-- Row Level Security + Storage
-- Default stance: nobody can do anything unless a policy says so.
-- The server (service role) bypasses RLS and is only used server-side.
-- =====================================================================

alter table public.settings       enable row level security;
alter table public.products       enable row level security;
alter table public.product_images enable row level security;
alter table public.batches        enable row level security;
alter table public.customers      enable row level security;
alter table public.orders         enable row level security;
alter table public.order_items    enable row level security;
alter table public.order_attempts enable row level security;

-- Explicit table grants (newer Supabase projects don't add these automatically).
-- RLS below still decides which ROWS each role can see or change.
grant usage on schema public to anon, authenticated, service_role;
grant select on public.products, public.product_images to anon;
grant select, insert, update, delete on all tables in schema public to authenticated, service_role;
grant usage, select on all sequences in schema public to authenticated, service_role;
revoke all on public.order_attempts from authenticated;

-- Public storefront: only visible products and their images.
create policy products_public_read on public.products
  for select to anon, authenticated
  using (is_active and deleted_at is null);

create policy product_images_public_read on public.product_images
  for select to anon, authenticated
  using (exists (
    select 1 from public.products p
    where p.id = product_id and p.is_active and p.deleted_at is null
  ));

-- Admin: full access everywhere.
create policy settings_admin       on public.settings       for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy products_admin       on public.products       for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy product_images_admin on public.product_images for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy batches_admin        on public.batches        for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy customers_admin      on public.customers      for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy orders_admin         on public.orders         for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy order_items_admin    on public.order_items    for all to authenticated using (public.is_admin()) with check (public.is_admin());
-- order_attempts: no policies → only the service role can touch it.

-- The admin may not change who the admin is from the app (prevents lock-out
-- and takeover); that is done in the SQL editor only.
create or replace function public.protect_admin_email() returns trigger
language plpgsql as $$
begin
  if new.admin_email is distinct from old.admin_email
     and current_user in ('authenticated', 'anon') then
    raise exception 'admin_email can only be changed in the Supabase SQL editor';
  end if;
  return new;
end $$;
create trigger settings_protect_admin before update on public.settings
  for each row execute function public.protect_admin_email();

-- Functions: lock down who may call what.
revoke execute on function public.get_or_create_batch(timestamptz) from public, anon, authenticated;
grant  execute on function public.get_or_create_batch(timestamptz) to service_role;
revoke execute on function public.is_admin() from public;
grant  execute on function public.is_admin() to anon, authenticated, service_role;
revoke execute on function public.get_public_settings() from public;
grant  execute on function public.get_public_settings() to anon, authenticated, service_role;

-- ---------------------------------------------------------------------
-- Storage buckets (public read; only the admin can write)
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('product-images', 'product-images', true, 5242880, array['image/webp', 'image/jpeg', 'image/png']),
  ('site',           'site',           true, 5242880, array['image/webp', 'image/jpeg', 'image/png'])
on conflict (id) do nothing;

-- Storage needs SELECT as well for delete/overwrite to work.
create policy storage_admin_select on storage.objects for select to authenticated
  using (bucket_id in ('product-images', 'site') and public.is_admin());
create policy storage_admin_insert on storage.objects for insert to authenticated
  with check (bucket_id in ('product-images', 'site') and public.is_admin());
create policy storage_admin_update on storage.objects for update to authenticated
  using (bucket_id in ('product-images', 'site') and public.is_admin());
create policy storage_admin_delete on storage.objects for delete to authenticated
  using (bucket_id in ('product-images', 'site') and public.is_admin());

-- ===== migrations/0003_function_search_path.sql =====
-- Hardening flagged by the Supabase security advisor: pin search_path on
-- trigger functions so they can't be tricked by a malicious schema.
alter function public.touch_updated_at() set search_path = public;
alter function public.protect_admin_email() set search_path = public;

-- ===== migrations/0004_product_category.sql =====
-- Product category (Hopia / Sweets, Crinkles, Polvoron, …) for grouping in the shop.
alter table public.products
  add column category text not null default 'Hopia / Sweets'
  check (length(trim(category)) between 1 and 40);
create index products_category_idx on public.products (category, sort_order);

-- ===== migrations/0005_supplier_price_optional.sql =====
-- Supplier price can be unknown for now. NULL means "not set yet" (not ₱0),
-- so profit stays NULL instead of showing a fake number.
alter table public.products alter column supplier_price drop not null;
alter table public.order_items alter column supplier_price drop not null;

-- ===== migrations/0006_orders.sql =====
-- =====================================================================
-- M2: placing and looking up orders
-- =====================================================================

-- Server-only secret: only our /api/orders route knows it, so nobody can
-- call create_order() directly and skip the rate limit. Lives in a schema
-- the public API does not expose.
-- A new schema grants nothing to anon/authenticated, so it stays private.
create schema if not exists private;
create table private.app_secrets (
  key   text primary key,
  value text not null
);
insert into private.app_secrets (key, value)
values ('order_api_secret', replace(gen_random_uuid()::text, '-', '') || replace(gen_random_uuid()::text, '-', ''))
on conflict (key) do nothing;

-- ---------------------------------------------------------------------
-- Which batch / delivery dates apply right now (read-only, for the shop)
-- ---------------------------------------------------------------------
create or replace function public.current_batch_preview(ts timestamptz default now())
returns table (code text, cutoff_at timestamptz, office_date date, outside_date date)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  s          public.settings;
  local_ts   timestamp := ts at time zone 'Asia/Manila';
  cutoff_day date;
  cutoff_end timestamptz;
begin
  return query
    select b.code, b.cutoff_at, b.office_date, b.outside_date
    from public.batches b where b.starts_at <= ts and ts < b.cutoff_at;
  if found then return; end if;

  select * into s from public.settings where id = 1;
  cutoff_day := local_ts::date + ((s.cutoff_dow - extract(dow from local_ts)::int + 7) % 7);
  cutoff_end := ((cutoff_day + s.cutoff_time) + interval '1 minute') at time zone 'Asia/Manila';
  if cutoff_end <= ts then
    cutoff_day := cutoff_day + 7;
    cutoff_end := cutoff_end + interval '7 days';
  end if;
  return query select to_char(cutoff_day, 'YYYY-MM-DD'), cutoff_end,
                      cutoff_day + s.office_offset_days, cutoff_day + s.outside_offset_days;
end $$;

-- ---------------------------------------------------------------------
-- Place an order. Prices always come from the database, never the cart.
-- ---------------------------------------------------------------------
create or replace function public.create_order(p jsonb, p_ip_hash text, p_secret text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_secret   text;
  v_batch    public.batches;
  v_customer uuid;
  v_order    public.orders;
  v_item     jsonb;
  v_product  public.products;
  v_total    numeric(10,2) := 0;
  v_count    int;
  v_name     text := trim(coalesce(p->>'name', ''));
  v_phone    text := trim(coalesce(p->>'phone', ''));
  v_address  text := trim(coalesce(p->>'address', ''));
  v_landmark text := trim(coalesce(p->>'landmark', ''));
  v_map      text := nullif(trim(coalesce(p->>'map_url', '')), '');
  v_notes    text := nullif(trim(coalesce(p->>'notes', '')), '');
  v_delivery public.delivery_type;
  v_payment  public.payment_method;
  v_items    jsonb := coalesce(p->'items', '[]'::jsonb);
begin
  select value into v_secret from private.app_secrets where key = 'order_api_secret';
  if p_secret is null or v_secret is null or p_secret <> v_secret then
    raise exception 'forbidden' using errcode = '42501';
  end if;

  -- Spam protection: max 5 orders per device/IP per hour.
  select count(*) into v_count from public.order_attempts
  where ip_hash = p_ip_hash and created_at > now() - interval '1 hour';
  if v_count >= 5 then
    raise exception 'rate_limited';
  end if;
  insert into public.order_attempts (ip_hash) values (p_ip_hash);

  -- Validation (the app validates too; this is the last line of defence)
  if length(v_name) < 2 or length(v_name) > 80 then raise exception 'invalid_name'; end if;
  if v_phone !~ '^\+639[0-9]{9}$' then raise exception 'invalid_phone'; end if;
  if length(v_address) < 5 or length(v_address) > 300 then raise exception 'invalid_address'; end if;
  if length(v_landmark) < 2 or length(v_landmark) > 200 then raise exception 'invalid_landmark'; end if;
  if v_map is not null and (length(v_map) > 500 or v_map !~ '^https://') then raise exception 'invalid_map_url'; end if;
  if v_notes is not null and length(v_notes) > 500 then raise exception 'invalid_notes'; end if;
  begin
    v_delivery := (p->>'delivery_type')::public.delivery_type;
    v_payment  := (p->>'payment_method')::public.payment_method;
  exception when others then
    raise exception 'invalid_choice';
  end;
  if v_delivery is null or v_payment is null then raise exception 'invalid_choice'; end if;
  if jsonb_typeof(v_items) <> 'array' or jsonb_array_length(v_items) = 0 or jsonb_array_length(v_items) > 40 then
    raise exception 'empty_cart';
  end if;

  v_batch := public.get_or_create_batch(now());

  insert into public.customers (phone, name) values (v_phone, v_name)
  on conflict (phone) do update set name = excluded.name
  returning id into v_customer;

  insert into public.orders (batch_id, customer_id, name, phone, delivery_type, address, landmark,
                             map_url, notes, delivery_date, payment_method, total)
  values (v_batch.id, v_customer, v_name, v_phone, v_delivery, v_address, v_landmark, v_map, v_notes,
          case when v_delivery = 'office' then v_batch.office_date else v_batch.outside_date end,
          v_payment, 0)
  returning * into v_order;

  for v_item in select * from jsonb_array_elements(v_items) loop
    if (v_item->>'qty') !~ '^[0-9]{1,2}$' or (v_item->>'qty')::int < 1 then
      raise exception 'invalid_qty';
    end if;
    select * into v_product from public.products
    where id = (v_item->>'product_id')::uuid and is_active and deleted_at is null;
    if not found then
      raise exception 'product_unavailable';
    end if;
    insert into public.order_items (order_id, product_id, product_name, qty, selling_price, supplier_price, delivery_markup)
    values (v_order.id, v_product.id, v_product.name, (v_item->>'qty')::int,
            v_product.selling_price, v_product.supplier_price, v_product.delivery_markup);
    v_total := v_total + v_product.selling_price * (v_item->>'qty')::int;
  end loop;

  update public.orders set total = v_total where id = v_order.id;

  return jsonb_build_object(
    'code', v_order.code,
    'total', v_total,
    'delivery_date', v_order.delivery_date,
    'delivery_type', v_delivery,
    'payment_method', v_payment
  );
end $$;

-- ---------------------------------------------------------------------
-- Customer order lookup: needs BOTH the order code and the phone number.
-- Returns no address or notes on purpose.
-- ---------------------------------------------------------------------
create or replace function public.lookup_order(p_code text, p_phone text)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'code', o.code,
    'name', o.name,
    'status', o.status,
    'paid', o.paid,
    'payment_method', o.payment_method,
    'delivery_type', o.delivery_type,
    'delivery_date', o.delivery_date,
    'total', o.total,
    'created_at', o.created_at,
    'items', coalesce((
      select jsonb_agg(jsonb_build_object('name', i.product_name, 'qty', i.qty, 'price', i.selling_price) order by i.product_name)
      from public.order_items i where i.order_id = o.id), '[]'::jsonb)
  )
  from public.orders o
  where o.code = upper(trim(p_code)) and o.phone = p_phone;
$$;

revoke execute on function public.current_batch_preview(timestamptz) from public;
grant  execute on function public.current_batch_preview(timestamptz) to anon, authenticated, service_role;
revoke execute on function public.create_order(jsonb, text, text) from public;
grant  execute on function public.create_order(jsonb, text, text) to anon, authenticated, service_role;
revoke execute on function public.lookup_order(text, text) from public;
grant  execute on function public.lookup_order(text, text) to anon, authenticated, service_role;

-- ===== migrations/0007_dashboard_traffic.sql =====
-- =====================================================================
-- Traffic tracking (privacy-friendly) + admin dashboard numbers
-- =====================================================================

-- One row per page view. visitor_id is a random id kept in the visitor's
-- browser: no cookies, no IP, no personal data.
create table public.page_views (
  id           bigint generated always as identity primary key,
  created_at   timestamptz not null default now(),
  visitor_id   text not null check (visitor_id ~ '^[a-z0-9-]{8,40}$'),
  path         text not null check (length(path) between 1 and 200),
  product_slug text,
  source       text not null default 'direct'
               check (source in ('facebook', 'messenger', 'instagram', 'google', 'direct', 'other'))
);
create index page_views_created_idx on public.page_views (created_at desc);
create index page_views_visitor_idx on public.page_views (visitor_id, path, created_at desc);
alter table public.page_views enable row level security;
create policy page_views_admin_read on public.page_views for select to authenticated using (public.is_admin());
grant select on public.page_views to authenticated;

-- Called by the shop in the browser. Ignores repeats of the same page by the
-- same visitor within 30 minutes, and caps total rows per day so a bot can't
-- fill the free database.
create or replace function public.track_view(p_visitor text, p_path text, p_source text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_path text := left(coalesce(p_path, '/'), 200);
  v_slug text;
begin
  if p_visitor !~ '^[a-z0-9-]{8,40}$' then return; end if;
  if p_source not in ('facebook', 'messenger', 'instagram', 'google', 'direct', 'other') then p_source := 'other'; end if;
  if v_path like '/admin%' or v_path like '/api%' then return; end if;

  if exists (select 1 from public.page_views
             where visitor_id = p_visitor and path = v_path and created_at > now() - interval '30 minutes') then
    return;
  end if;
  if (select count(*) from public.page_views where visitor_id = p_visitor and created_at > now() - interval '1 day') >= 300 then
    return;
  end if;
  if (select count(*) from public.page_views where created_at > now() - interval '1 day') >= 20000 then
    return;
  end if;

  if v_path like '/p/%' then v_slug := split_part(substr(v_path, 4), '/', 1); end if;
  insert into public.page_views (visitor_id, path, product_slug, source) values (p_visitor, v_path, v_slug, p_source);
end $$;

-- ---------------------------------------------------------------------
-- Admin-only dashboard numbers for one batch (default: current batch)
-- ---------------------------------------------------------------------
create or replace function public.admin_dashboard(p_batch_id uuid default null, p_days int default 7)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_batch public.batches;
  v_since timestamptz := now() - make_interval(days => greatest(1, least(p_days, 90)));
  v_today timestamptz := date_trunc('day', now() at time zone 'Asia/Manila') at time zone 'Asia/Manila';
  out jsonb;
begin
  if not public.is_admin() then
    raise exception 'forbidden' using errcode = '42501';
  end if;

  if p_batch_id is not null then
    select * into v_batch from public.batches where id = p_batch_id;
  else
    select * into v_batch from public.batches where starts_at <= now() and now() < cutoff_at;
  end if;

  with o as (
    select * from public.orders where batch_id = v_batch.id and status <> 'cancelled'
  ), i as (
    select i.* from public.order_items i join o on o.id = i.order_id
  )
  select jsonb_build_object(
    'batch', case when v_batch.id is null then null else to_jsonb(v_batch) end,
    'orders',            (select count(*) from o),
    'sales',             coalesce((select sum(total) from o), 0),
    'unpaid',            coalesce((select sum(total) from o where not paid), 0),
    'unpaid_orders',     (select count(*) from o where not paid),
    'profit_known',      coalesce((select sum((selling_price - delivery_markup - supplier_price) * qty) from i where supplier_price is not null), 0),
    'items_no_supplier', (select count(*) from i where supplier_price is null),
    'delivery_fund',     coalesce((select sum(delivery_markup * qty) from i), 0),
    'supplier_cost',     coalesce((select sum(supplier_price * qty) from i where supplier_price is not null), 0),
    'pieces',            coalesce((select sum(qty) from i), 0),
    'by_status',   (select coalesce(jsonb_object_agg(status, n), '{}') from (select status, count(*) n from public.orders where batch_id = v_batch.id group by status) s),
    'by_delivery', (select coalesce(jsonb_object_agg(delivery_type, n), '{}') from (select delivery_type, count(*) n from o group by delivery_type) s),
    'by_payment',  (select coalesce(jsonb_object_agg(payment_method, n), '{}') from (select payment_method, count(*) n from o group by payment_method) s),
    'top_products', (select coalesce(jsonb_agg(t order by t.qty desc), '[]') from (
                       select product_name as name, sum(qty) as qty, sum(selling_price * qty) as sales
                       from i group by product_name order by sum(qty) desc limit 5) t),
    'new_orders',  (select count(*) from public.orders where not seen_by_admin),
    'repeat_customers', (select count(*) from (select customer_id from public.orders where status <> 'cancelled'
                                               group by customer_id having count(*) > 1) r),
    'traffic', jsonb_build_object(
      'days', greatest(1, least(p_days, 90)),
      'visitors_today', (select count(distinct visitor_id) from public.page_views where created_at >= v_today),
      'visitors',       (select count(distinct visitor_id) from public.page_views where created_at >= v_since),
      'views',          (select count(*) from public.page_views where created_at >= v_since),
      'orders',         (select count(*) from public.orders where created_at >= v_since and status <> 'cancelled'),
      'sources', (select coalesce(jsonb_agg(s order by s.visitors desc), '[]') from (
                    select source, count(distinct visitor_id) as visitors from public.page_views
                    where created_at >= v_since group by source) s),
      'top_viewed', (select coalesce(jsonb_agg(t order by t.views desc), '[]') from (
                       select pv.product_slug as slug, coalesce(p.name, pv.product_slug) as name, count(*) as views
                       from public.page_views pv left join public.products p on p.slug = pv.product_slug
                       where pv.created_at >= v_since and pv.product_slug is not null
                       group by pv.product_slug, p.name order by count(*) desc limit 5) t),
      'daily', (select coalesce(jsonb_agg(d order by d.day), '[]') from (
                  select to_char(gs.day, 'YYYY-MM-DD') as day,
                         (select count(distinct visitor_id) from public.page_views
                          where (created_at at time zone 'Asia/Manila')::date = gs.day) as visitors
                  from generate_series((now() at time zone 'Asia/Manila')::date - (greatest(1, least(p_days, 90)) - 1),
                                       (now() at time zone 'Asia/Manila')::date, interval '1 day') as gs(day)) d)
    )
  ) into out;
  return out;
end $$;

-- Per-product totals for the supplier order (non-cancelled orders only).
create or replace function public.batch_summary(p_batch_id uuid)
returns table (product_name text, qty bigint, supplier_price numeric, supplier_cost numeric, sales numeric)
language sql
stable
security definer
set search_path = public
as $$
  select i.product_name, sum(i.qty), max(i.supplier_price),
         sum(i.supplier_price * i.qty), sum(i.selling_price * i.qty)
  from public.order_items i
  join public.orders o on o.id = i.order_id
  where public.is_admin() and o.batch_id = p_batch_id and o.status <> 'cancelled'
  group by i.product_name
  order by i.product_name;
$$;

-- ===== migrations/0008_lh_order_prefix.sql =====
-- Store renamed to Lhyndahan: order codes are now LH-0001 (was RH-0001).
-- Fresh databases already get LH- from 0001; this only converts a database created before the rename.
do $$
declare cur text;
begin
  select pg_get_expr(d.adbin, d.adrelid) into cur
  from pg_attrdef d join pg_attribute a on a.attrelid = d.adrelid and a.attnum = d.adnum
  where d.adrelid = 'public.orders'::regclass and a.attname = 'code';
  if cur like '%RH-%' then
    execute $q$alter table public.orders alter column code set expression as (
      'LH-' || case when order_no < 10000 then lpad(order_no::text, 4, '0') else order_no::text end
    )$q$;
  end if;
end $$;

-- ===== migrations/0009_kus_delivery.sql =====
-- KUS delivery ("office") is delivered on-site: no address, landmark or map pin is collected.
-- The server enforces this (ignores whatever the client sent) and stores 'KUS' as the address
-- so lists and exports still show where the order goes.
create or replace function public.create_order(p jsonb, p_ip_hash text, p_secret text)
 returns jsonb
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_secret   text;
  v_batch    public.batches;
  v_customer uuid;
  v_order    public.orders;
  v_item     jsonb;
  v_product  public.products;
  v_total    numeric(10,2) := 0;
  v_count    int;
  v_name     text := trim(coalesce(p->>'name', ''));
  v_phone    text := trim(coalesce(p->>'phone', ''));
  v_address  text := trim(coalesce(p->>'address', ''));
  v_landmark text := trim(coalesce(p->>'landmark', ''));
  v_map      text := nullif(trim(coalesce(p->>'map_url', '')), '');
  v_notes    text := nullif(trim(coalesce(p->>'notes', '')), '');
  v_delivery public.delivery_type;
  v_payment  public.payment_method;
  v_items    jsonb := coalesce(p->'items', '[]'::jsonb);
begin
  select value into v_secret from private.app_secrets where key = 'order_api_secret';
  if p_secret is null or v_secret is null or p_secret <> v_secret then
    raise exception 'forbidden' using errcode = '42501';
  end if;

  select count(*) into v_count from public.order_attempts
  where ip_hash = p_ip_hash and created_at > now() - interval '1 hour';
  if v_count >= 5 then
    raise exception 'rate_limited';
  end if;
  insert into public.order_attempts (ip_hash) values (p_ip_hash);

  if length(v_name) < 2 or length(v_name) > 80 then raise exception 'invalid_name'; end if;
  if v_phone !~ '^\+639[0-9]{9}$' then raise exception 'invalid_phone'; end if;
  if v_notes is not null and length(v_notes) > 500 then raise exception 'invalid_notes'; end if;
  begin
    v_delivery := (p->>'delivery_type')::public.delivery_type;
    v_payment  := (p->>'payment_method')::public.payment_method;
  exception when others then
    raise exception 'invalid_choice';
  end;
  if v_delivery is null or v_payment is null then raise exception 'invalid_choice'; end if;

  if v_delivery = 'office' then
    v_address := 'KUS';
    v_landmark := '';
    v_map := null;
  else
    if length(v_address) < 5 or length(v_address) > 300 then raise exception 'invalid_address'; end if;
    if length(v_landmark) < 2 or length(v_landmark) > 200 then raise exception 'invalid_landmark'; end if;
    if v_map is not null and (length(v_map) > 500 or v_map !~ '^https://') then raise exception 'invalid_map_url'; end if;
  end if;

  if jsonb_typeof(v_items) <> 'array' or jsonb_array_length(v_items) = 0 or jsonb_array_length(v_items) > 40 then
    raise exception 'empty_cart';
  end if;

  v_batch := public.get_or_create_batch(now());

  insert into public.customers (phone, name) values (v_phone, v_name)
  on conflict (phone) do update set name = excluded.name
  returning id into v_customer;

  insert into public.orders (batch_id, customer_id, name, phone, delivery_type, address, landmark,
                             map_url, notes, delivery_date, payment_method, total)
  values (v_batch.id, v_customer, v_name, v_phone, v_delivery, v_address, v_landmark, v_map, v_notes,
          case when v_delivery = 'office' then v_batch.office_date else v_batch.outside_date end,
          v_payment, 0)
  returning * into v_order;

  for v_item in select * from jsonb_array_elements(v_items) loop
    if (v_item->>'qty') !~ '^[0-9]{1,2}$' or (v_item->>'qty')::int < 1 then
      raise exception 'invalid_qty';
    end if;
    select * into v_product from public.products
    where id = (v_item->>'product_id')::uuid and is_active and deleted_at is null;
    if not found then
      raise exception 'product_unavailable';
    end if;
    insert into public.order_items (order_id, product_id, product_name, qty, selling_price, supplier_price, delivery_markup)
    values (v_order.id, v_product.id, v_product.name, (v_item->>'qty')::int,
            v_product.selling_price, v_product.supplier_price, v_product.delivery_markup);
    v_total := v_total + v_product.selling_price * (v_item->>'qty')::int;
  end loop;

  update public.orders set total = v_total where id = v_order.id;

  return jsonb_build_object(
    'code', v_order.code,
    'total', v_total,
    'delivery_date', v_order.delivery_date,
    'delivery_type', v_delivery,
    'payment_method', v_payment
  );
end $function$;

-- ===== migrations/0010_address_checks_outside_only.sql =====
-- KUS (office) orders carry no street address or landmark, so only enforce them for outside delivery.
alter table public.orders drop constraint orders_address_check, drop constraint orders_landmark_check;
alter table public.orders
  add constraint orders_address_check check (delivery_type = 'office' or length(trim(address)) >= 5),
  add constraint orders_landmark_check check (delivery_type = 'office' or length(trim(landmark)) >= 2);

-- ===== migrations/0011_payment_method_qr.sql =====
-- "QR Code payment" replaces the GCash-only option. Old 'gcash' orders keep working.
alter type public.payment_method add value if not exists 'qr';

-- ===== migrations/0012_payment_qrs.sql =====
-- Payment QR codes managed from the admin (GCash, Maya, bank, ...). Shown to the customer after they order.
create table public.payment_qrs (
  id             uuid primary key default gen_random_uuid(),
  label          text not null check (length(trim(label)) between 1 and 40),
  account_name   text check (account_name is null or length(account_name) <= 80),
  account_number text check (account_number is null or length(account_number) <= 40),
  image_path     text not null check (image_path like 'qr/%' and image_path not like '%..%'),
  sort_order     int not null default 0,
  is_active      boolean not null default true,
  created_at     timestamptz not null default now()
);
alter table public.payment_qrs enable row level security;
create policy payment_qrs_public_read on public.payment_qrs for select using (is_active);
create policy payment_qrs_admin on public.payment_qrs for all using (public.is_admin()) with check (public.is_admin());
grant select on public.payment_qrs to anon;
grant select, insert, update, delete on public.payment_qrs to authenticated, service_role;

alter table public.orders
  add column qr_id uuid references public.payment_qrs(id) on delete set null,
  add column qr_provider text;

create or replace function public.create_order(p jsonb, p_ip_hash text, p_secret text)
 returns jsonb
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_secret   text;
  v_batch    public.batches;
  v_customer uuid;
  v_order    public.orders;
  v_item     jsonb;
  v_product  public.products;
  v_total    numeric(10,2) := 0;
  v_count    int;
  v_name     text := trim(coalesce(p->>'name', ''));
  v_phone    text := trim(coalesce(p->>'phone', ''));
  v_address  text := trim(coalesce(p->>'address', ''));
  v_landmark text := trim(coalesce(p->>'landmark', ''));
  v_map      text := nullif(trim(coalesce(p->>'map_url', '')), '');
  v_notes    text := nullif(trim(coalesce(p->>'notes', '')), '');
  v_delivery public.delivery_type;
  v_payment  public.payment_method;
  v_qr_id    uuid;
  v_qr_label text;
  v_qr_ref   uuid;
  v_items    jsonb := coalesce(p->'items', '[]'::jsonb);
begin
  select value into v_secret from private.app_secrets where key = 'order_api_secret';
  if p_secret is null or v_secret is null or p_secret <> v_secret then
    raise exception 'forbidden' using errcode = '42501';
  end if;

  select count(*) into v_count from public.order_attempts
  where ip_hash = p_ip_hash and created_at > now() - interval '1 hour';
  if v_count >= 5 then
    raise exception 'rate_limited';
  end if;
  insert into public.order_attempts (ip_hash) values (p_ip_hash);

  if length(v_name) < 2 or length(v_name) > 80 then raise exception 'invalid_name'; end if;
  if v_phone !~ '^\+639[0-9]{9}$' then raise exception 'invalid_phone'; end if;
  if v_notes is not null and length(v_notes) > 500 then raise exception 'invalid_notes'; end if;
  begin
    v_delivery := (p->>'delivery_type')::public.delivery_type;
    v_payment  := (p->>'payment_method')::public.payment_method;
  exception when others then
    raise exception 'invalid_choice';
  end;
  if v_delivery is null or v_payment is null then raise exception 'invalid_choice'; end if;

  if v_payment = 'gcash' then raise exception 'invalid_choice'; end if; -- legacy value, not accepted for new orders
  if v_payment = 'qr' then
    begin
      v_qr_id := (p->>'qr_id')::uuid;
    exception when others then
      raise exception 'invalid_choice';
    end;
    select id, label into v_qr_ref, v_qr_label from public.payment_qrs where id = v_qr_id and is_active;
    if v_qr_ref is null then raise exception 'invalid_choice'; end if;
  end if;

  if v_delivery = 'office' then
    v_address := 'KUS';
    v_landmark := '';
    v_map := null;
  else
    if length(v_address) < 5 or length(v_address) > 300 then raise exception 'invalid_address'; end if;
    if length(v_landmark) < 2 or length(v_landmark) > 200 then raise exception 'invalid_landmark'; end if;
    if v_map is not null and (length(v_map) > 500 or v_map !~ '^https://') then raise exception 'invalid_map_url'; end if;
  end if;

  if jsonb_typeof(v_items) <> 'array' or jsonb_array_length(v_items) = 0 or jsonb_array_length(v_items) > 40 then
    raise exception 'empty_cart';
  end if;

  v_batch := public.get_or_create_batch(now());

  insert into public.customers (phone, name) values (v_phone, v_name)
  on conflict (phone) do update set name = excluded.name
  returning id into v_customer;

  insert into public.orders (batch_id, customer_id, name, phone, delivery_type, address, landmark,
                             map_url, notes, delivery_date, payment_method, qr_id, qr_provider, total)
  values (v_batch.id, v_customer, v_name, v_phone, v_delivery, v_address, v_landmark, v_map, v_notes,
          case when v_delivery = 'office' then v_batch.office_date else v_batch.outside_date end,
          v_payment, v_qr_ref, v_qr_label, 0)
  returning * into v_order;

  for v_item in select * from jsonb_array_elements(v_items) loop
    if (v_item->>'qty') !~ '^[0-9]{1,2}$' or (v_item->>'qty')::int < 1 then
      raise exception 'invalid_qty';
    end if;
    select * into v_product from public.products
    where id = (v_item->>'product_id')::uuid and is_active and deleted_at is null;
    if not found then
      raise exception 'product_unavailable';
    end if;
    insert into public.order_items (order_id, product_id, product_name, qty, selling_price, supplier_price, delivery_markup)
    values (v_order.id, v_product.id, v_product.name, (v_item->>'qty')::int,
            v_product.selling_price, v_product.supplier_price, v_product.delivery_markup);
    v_total := v_total + v_product.selling_price * (v_item->>'qty')::int;
  end loop;

  update public.orders set total = v_total where id = v_order.id;

  return jsonb_build_object(
    'code', v_order.code,
    'total', v_total,
    'delivery_date', v_order.delivery_date,
    'delivery_type', v_delivery,
    'payment_method', v_payment,
    'qr_provider', v_qr_label
  );
end $function$;


create or replace function public.lookup_order(p_code text, p_phone text)
 returns jsonb
 language sql
 stable security definer
 set search_path to 'public'
as $function$
  select jsonb_build_object(
    'code', o.code,
    'name', o.name,
    'status', o.status,
    'paid', o.paid,
    'payment_method', o.payment_method,
    'qr_id', o.qr_id,
    'qr_provider', o.qr_provider,
    'delivery_type', o.delivery_type,
    'delivery_date', o.delivery_date,
    'total', o.total,
    'created_at', o.created_at,
    'items', coalesce((
      select jsonb_agg(jsonb_build_object('name', i.product_name, 'qty', i.qty, 'price', i.selling_price) order by i.product_name)
      from public.order_items i where i.order_id = o.id), '[]'::jsonb)
  )
  from public.orders o
  where o.code = upper(trim(p_code)) and o.phone = p_phone;
$function$;

-- ===== migrations/0013_anon_least_privilege.sql =====
-- The public (anon) role only needs to read the storefront tables. Everything else goes
-- through SECURITY DEFINER functions, so remove every other privilege as a second lock
-- behind row level security.
revoke all on all tables in schema public from anon;
revoke all on all sequences in schema public from anon;
grant select on public.products, public.product_images, public.payment_qrs to anon;

-- ===== migrations/0014_abuse_limits_and_retention.sql =====
-- Abuse protection and data retention.
--  * lookup_order: max 10 wrong guesses per hour per order code and per phone number
--  * create_order: max 5 orders per hour per phone number (on top of the per-IP limit);
--    an order no longer renames an existing customer record
--  * purge_old_data(): clears old attempt logs and anonymises personal details of orders
--    older than 180 days (sales history is kept), scheduled daily with pg_cron

create table public.lookup_attempts (
  id         bigint generated always as identity primary key,
  phone      text not null,
  code       text not null,
  created_at timestamptz not null default now()
);
create index lookup_attempts_phone_idx on public.lookup_attempts (phone, created_at desc);
create index lookup_attempts_code_idx  on public.lookup_attempts (code, created_at desc);
alter table public.lookup_attempts enable row level security;
revoke all on public.lookup_attempts from anon, authenticated;

create or replace function public.lookup_order(p_code text, p_phone text)
 returns jsonb
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_code  text := left(upper(trim(coalesce(p_code, ''))), 20);
  v_phone text := left(trim(coalesce(p_phone, '')), 20);
  v_res   jsonb;
begin
  if (select count(*) from public.lookup_attempts
      where created_at > now() - interval '1 hour' and (phone = v_phone or code = v_code)) >= 10 then
    raise exception 'rate_limited';
  end if;

  select jsonb_build_object(
    'code', o.code,
    'name', o.name,
    'status', o.status,
    'paid', o.paid,
    'payment_method', o.payment_method,
    'qr_id', o.qr_id,
    'qr_provider', o.qr_provider,
    'delivery_type', o.delivery_type,
    'delivery_date', o.delivery_date,
    'total', o.total,
    'created_at', o.created_at,
    'items', coalesce((
      select jsonb_agg(jsonb_build_object('name', i.product_name, 'qty', i.qty, 'price', i.selling_price) order by i.product_name)
      from public.order_items i where i.order_id = o.id), '[]'::jsonb)
  ) into v_res
  from public.orders o
  where o.code = v_code and o.phone = v_phone;

  if v_res is null then
    insert into public.lookup_attempts (phone, code) values (v_phone, v_code);
  end if;
  return v_res;
end $function$;

create or replace function public.create_order(p jsonb, p_ip_hash text, p_secret text)
 returns jsonb
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_secret   text;
  v_batch    public.batches;
  v_customer uuid;
  v_order    public.orders;
  v_item     jsonb;
  v_product  public.products;
  v_total    numeric(10,2) := 0;
  v_count    int;
  v_name     text := trim(coalesce(p->>'name', ''));
  v_phone    text := trim(coalesce(p->>'phone', ''));
  v_address  text := trim(coalesce(p->>'address', ''));
  v_landmark text := trim(coalesce(p->>'landmark', ''));
  v_map      text := nullif(trim(coalesce(p->>'map_url', '')), '');
  v_notes    text := nullif(trim(coalesce(p->>'notes', '')), '');
  v_delivery public.delivery_type;
  v_payment  public.payment_method;
  v_qr_id    uuid;
  v_qr_label text;
  v_qr_ref   uuid;
  v_items    jsonb := coalesce(p->'items', '[]'::jsonb);
begin
  select value into v_secret from private.app_secrets where key = 'order_api_secret';
  if p_secret is null or v_secret is null or p_secret <> v_secret then
    raise exception 'forbidden' using errcode = '42501';
  end if;

  select count(*) into v_count from public.order_attempts
  where ip_hash = p_ip_hash and created_at > now() - interval '1 hour';
  if v_count >= 5 then
    raise exception 'rate_limited';
  end if;
  insert into public.order_attempts (ip_hash) values (p_ip_hash);

  -- Also cap per phone number, so rotating IPs can't flood one person's number with orders.
  if (select count(*) from public.orders where phone = trim(coalesce(p->>'phone', '')) and created_at > now() - interval '1 hour') >= 5 then
    raise exception 'rate_limited';
  end if;

  if length(v_name) < 2 or length(v_name) > 80 then raise exception 'invalid_name'; end if;
  if v_phone !~ '^\+639[0-9]{9}$' then raise exception 'invalid_phone'; end if;
  if v_notes is not null and length(v_notes) > 500 then raise exception 'invalid_notes'; end if;
  begin
    v_delivery := (p->>'delivery_type')::public.delivery_type;
    v_payment  := (p->>'payment_method')::public.payment_method;
  exception when others then
    raise exception 'invalid_choice';
  end;
  if v_delivery is null or v_payment is null then raise exception 'invalid_choice'; end if;

  if v_payment = 'gcash' then raise exception 'invalid_choice'; end if; -- legacy value, not accepted for new orders
  if v_payment = 'qr' then
    begin
      v_qr_id := (p->>'qr_id')::uuid;
    exception when others then
      raise exception 'invalid_choice';
    end;
    select id, label into v_qr_ref, v_qr_label from public.payment_qrs where id = v_qr_id and is_active;
    if v_qr_ref is null then raise exception 'invalid_choice'; end if;
  end if;

  if v_delivery = 'office' then
    v_address := 'KUS';
    v_landmark := '';
    v_map := null;
  else
    if length(v_address) < 5 or length(v_address) > 300 then raise exception 'invalid_address'; end if;
    if length(v_landmark) < 2 or length(v_landmark) > 200 then raise exception 'invalid_landmark'; end if;
    if v_map is not null and (length(v_map) > 500 or v_map !~ '^https://') then raise exception 'invalid_map_url'; end if;
  end if;

  if jsonb_typeof(v_items) <> 'array' or jsonb_array_length(v_items) = 0 or jsonb_array_length(v_items) > 40 then
    raise exception 'empty_cart';
  end if;

  v_batch := public.get_or_create_batch(now());

  insert into public.customers (phone, name) values (v_phone, v_name)
  on conflict (phone) do update set phone = excluded.phone
  returning id into v_customer;

  insert into public.orders (batch_id, customer_id, name, phone, delivery_type, address, landmark,
                             map_url, notes, delivery_date, payment_method, qr_id, qr_provider, total)
  values (v_batch.id, v_customer, v_name, v_phone, v_delivery, v_address, v_landmark, v_map, v_notes,
          case when v_delivery = 'office' then v_batch.office_date else v_batch.outside_date end,
          v_payment, v_qr_ref, v_qr_label, 0)
  returning * into v_order;

  for v_item in select * from jsonb_array_elements(v_items) loop
    if (v_item->>'qty') !~ '^[0-9]{1,2}$' or (v_item->>'qty')::int < 1 then
      raise exception 'invalid_qty';
    end if;
    select * into v_product from public.products
    where id = (v_item->>'product_id')::uuid and is_active and deleted_at is null;
    if not found then
      raise exception 'product_unavailable';
    end if;
    insert into public.order_items (order_id, product_id, product_name, qty, selling_price, supplier_price, delivery_markup)
    values (v_order.id, v_product.id, v_product.name, (v_item->>'qty')::int,
            v_product.selling_price, v_product.supplier_price, v_product.delivery_markup);
    v_total := v_total + v_product.selling_price * (v_item->>'qty')::int;
  end loop;

  update public.orders set total = v_total where id = v_order.id;

  return jsonb_build_object(
    'code', v_order.code,
    'total', v_total,
    'delivery_date', v_order.delivery_date,
    'delivery_type', v_delivery,
    'payment_method', v_payment,
    'qr_provider', v_qr_label
  );
end $function$;;


create sequence public.anon_phone_seq;

create or replace function public.purge_old_data()
 returns void
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
begin
  delete from public.order_attempts  where created_at < now() - interval '2 days';
  delete from public.lookup_attempts where created_at < now() - interval '2 days';
  delete from public.page_views      where created_at < now() - interval '90 days';

  -- Personal details of old orders are removed; items, totals and dates stay for sales history.
  update public.orders
     set name = 'Removed', phone = '+639' || lpad(nextval('public.anon_phone_seq')::text, 9, '0'),
         address = 'Removed', landmark = 'Removed', map_url = null, notes = null
   where created_at < now() - interval '180 days' and name <> 'Removed';

  update public.customers
     set name = 'Removed', phone = '+639' || lpad(nextval('public.anon_phone_seq')::text, 9, '0')
   where created_at < now() - interval '180 days' and name <> 'Removed'
     and not exists (select 1 from public.orders o where o.customer_id = customers.id and o.created_at >= now() - interval '180 days');
end $function$;

revoke execute on function public.purge_old_data() from public, anon, authenticated;

-- Run the cleanup every day at 03:30 Philippine time (19:30 UTC). Skipped where pg_cron isn't available.
do $$
begin
  create extension if not exists pg_cron with schema pg_catalog;
  perform cron.schedule('purge-old-data', '30 19 * * *', 'select public.purge_old_data()');
exception when others then
  raise notice 'pg_cron not available here: run select public.purge_old_data() daily instead.';
end $$;

-- ===== seed.sql =====
-- Product list from the owner (selling prices). Supplier price is left NULL
-- (not set yet) so no fake profit shows until it is filled in /admin/products.
insert into public.products (slug, name, bakery, category, description, supplier_price, selling_price, delivery_markup, is_active, sort_order) values
('hopia-monggo-x10', 'Hopia Monggo x10', 'Ribbonets', 'Hopia / Sweets', '', null, 90, 10, true, 0),
('hopia-baboy-x10', 'Hopia Baboy x10', 'Ribbonets', 'Hopia / Sweets', '', null, 90, 10, true, 1),
('hopia-pandan', 'Hopia Pandan', 'Ribbonets', 'Hopia / Sweets', '', null, 90, 10, true, 2),
('hopia-dahon-sibuyas', 'Hopia Dahon Sibuyas', 'Ribbonets', 'Hopia / Sweets', '', null, 90, 10, true, 3),
('ube-deleche', 'Ube Deleche', 'Ribbonets', 'Hopia / Sweets', '', null, 110, 10, true, 4),
('ube-hopia-spl', 'Ube Hopia SPL', 'Ribbonets', 'Hopia / Sweets', '', null, 90, 10, true, 5),
('ube-regular', 'Ube Regular', 'Ribbonets', 'Hopia / Sweets', '', null, 90, 10, true, 6),
('yema-hopia', 'Yema Hopia', 'Ribbonets', 'Hopia / Sweets', '', null, 115, 10, true, 7),
('pastillas-deleche', 'Pastillas Deleche', 'Ribbonets', 'Hopia / Sweets', '', null, 110, 10, true, 8),
('cookies-cream', 'Cookies & Cream', 'Ribbonets', 'Hopia / Sweets', '', null, 125, 10, true, 9),
('choco-fudge', 'Choco Fudge', 'Ribbonets', 'Hopia / Sweets', '', null, 115, 10, true, 10),
('sweet-cassie-ube-spl-hopia', 'Ube SPL Hopia', 'Ribbonets', 'Sweet Cassie', '', null, 90, 10, true, 100),
('sweet-cassie-ube-regular-hopia', 'Ube Regular Hopia', 'Ribbonets', 'Sweet Cassie', '', null, 90, 10, true, 101),
('sweet-cassie-mongo-hopia', 'Mongo Hopia', 'Ribbonets', 'Sweet Cassie', '', null, 90, 10, true, 102),
('sweet-cassie-pastillas-de-yema', 'Pastillas de Yema', 'Ribbonets', 'Sweet Cassie', '', null, 115, 10, true, 103),
('crinkles-x10', 'Crinkles x10', 'Ribbonets', 'Crinkles', '', null, 60, 10, true, 200),
('crinkles-x18', 'Crinkles x18', 'Ribbonets', 'Crinkles', '', null, 110, 10, true, 201),
('crinkles-x20', 'Crinkles x20', 'Ribbonets', 'Crinkles', '', null, 120, 10, true, 202),
('crinkles-x30', 'Crinkles x30', 'Ribbonets', 'Crinkles', '', null, 80, 10, true, 203),
('polvoron-big', 'Polvoron Big', 'Ribbonets', 'Polvoron', '', null, 135, 10, true, 300),
('polvoron-small', 'Polvoron Small', 'Ribbonets', 'Polvoron', '', null, 100, 10, true, 301),
('polvoron-cookies-cream', 'Polvoron Cookies & Cream', 'Ribbonets', 'Polvoron', '', null, 140, 10, true, 302),
('cheese-cake-x1', 'Cheese Cake x1', 'Ribbonets', 'Cheesecake', '', null, 15, 10, true, 400),
('cheese-cake-x2', 'Cheese Cake x2', 'Ribbonets', 'Cheesecake', '', null, 30, 10, true, 401),
('cheese-cake-x4-cp', 'Cheese Cake x4 CP', 'Ribbonets', 'Cheesecake', '', null, 60, 10, true, 402),
('cheese-cake-x6', 'Cheese Cake x6', 'Ribbonets', 'Cheesecake', '', null, 90, 10, true, 403),
('cheese-cake-x8-cp', 'Cheese Cake x8 CP', 'Ribbonets', 'Cheesecake', '', null, 120, 10, true, 404),
('cheese-bulilit-x6', 'Cheese Bulilit x6', 'Ribbonets', 'Cheese Bulilit', '', null, 35, 10, true, 500),
('cheese-bulilit-x12', 'Cheese Bulilit x12', 'Ribbonets', 'Cheese Bulilit', '', null, 55, 10, true, 501)
on conflict (slug) do nothing;
